version: '3.8'

volumes:
  redis-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT:  bullseye
    env_file:
      - .env
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:redis
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/var/lib/redis
    command: redis-server --appendonly yes
